apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-appgke-wrong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-appgke-wrong
  template:
    metadata:
      labels:
        app: python-appgke-wrong
    spec:
      containers:
      - name: python-appgke-wrong
        image: gcr.io/clustergke-453308/python-appgke-wrong:icai20205
        imagePullPolicy: Always
        ports:
        - containerPort: 8080


