apiVersion: v1
kind: Service
metadata:
  name: python-appgke-wrong-service
spec:
  type: LoadBalancer
  selector:
    app: python-appgke-wrong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
